# Generated by Django 4.2.2 on 2023-07-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0005_products_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
    ]
