# Generated by Django 4.2.2 on 2023-10-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0008_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Barcode',
        ),
    ]
