# Generated by Django 4.2.2 on 2023-10-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0010_remove_barcode_country_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barcode',
            old_name='random',
            new_name='barcodeNo',
        ),
    ]
