# Generated by Django 4.2.2 on 2023-10-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0011_rename_random_barcode_barcodeno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='barcode',
            field=models.FileField(blank=True, upload_to='barcodes/'),
        ),
    ]
