# Generated by Django 4.2.2 on 2023-12-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0015_alter_barcode_barcodeno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='barcodeNo',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
